### ISSUE TITLE
blue screen without any logs

### ISSUE THREAD

**Issue by vuhailongkl97** [nguyenzung/kos#13]
Hi, 
I checked out the newest source and after I made it run qemu I didn't get any logs, Please check some recent merged commits, I reset to a commit in yesterday it worked well.

![image](https://user-images.githubusercontent.com/33160706/192811567-0687c9ac-623e-45e1-9e3d-399d70898e54.png)

**Comment by nguyenzung** [comment]
I added exception handler to handle vector from 0 -> 31 and did some testings with the commit.
Now it became normal.

**Comment by vuhailongkl97** [comment]
I checked. the error still happen.

**Comment by nguyenzung** [comment]
Please check again. I fixed a bug relate to compiler optimization that make stack crash

**Comment by vuhailongkl97** [comment]
it still happen

**Comment by nguyenzung** [comment]
I run normally on both Qemu and VirtualBox. 
Did you make clean? Or please recheck your toolchain in case it uses some default configure

**Comment by vuhailongkl97** [comment]
@nguyenzung 
I found that is my laptop problem whose CPU is Ryzen, It's ok with Ubuntu and a CPU intel. 
Do you have any idea to solve that?

**Comment by nguyenzung** [comment]
Maybe it relate to a problem when i added naked handleException that gcc support. Did you setup cross-compile ? I remember in a commit, you added a feature that require stdlib, and i had to add flag -std to bypass that, but i saw you did not need to do that

**Comment by vuhailongkl97** [comment]
my PC's architect  is x86_64 so I don't need to use cross-compile, why did you think it was related to stdlib ?

**Comment by ZungNguyen-Ekoios** [comment]
To be honest, i am not sure. But if you don't setup cross-compile, there maybe some issue with linking step, your linker will link with stuffs that are used by the host OS.

**Comment by vuhailongkl97** [comment]
I met a deadlock, I created a PR.
