### ISSUE TITLE
Can't boot 'KOS'

### ISSUE THREAD

**Issue by mountto** [nguyenzung/kos#25]
hi guys. something wrong with kernel.bin, Look my screen capture

![Screenshot from 2022-10-06 09-15-55](https://user-images.githubusercontent.com/85049064/194322667-65c85883-4591-49e0-a73c-624688498c1c.png)

**Comment by nguyenzung** [comment]
I think because your VM config. Did you choose x64 setting?

![Screenshot from 2022-10-06 21-57-11](https://user-images.githubusercontent.com/57292598/194347115-9c2ed82f-7051-40a6-ac42-cdd16818a80e.png)

**Comment by nguyenzung** [comment]
You also have to use KOS.iso . If you use kernel.bin, it cannot be loaded because there is no boot loader in KOS

**Comment by mountto** [comment]
qemu can't boot
![Screenshot from 2022-10-06 11-06-05](https://user-images.githubusercontent.com/85049064/194349173-1b906692-adc8-4512-b673-b1e51e05b0bb.png)

**Comment by nguyenzung** [comment]
Did you try run command "make demo"?

**Comment by mountto** [comment]
> I think because your VM config. Did you choose x64 setting?
> 
> ![Screenshot from 2022-10-06 21-57-11](https://user-images.githubusercontent.com/57292598/194347115-9c2ed82f-7051-40a6-ac42-cdd16818a80e.png)

**Comment by mountto** [comment]
i think, i know this fix

**Comment by mountto** [comment]
> i think, i know this fix

it wrong addr of GDT

**Comment by ZungNguyen-Ekoios** [comment]
Did you change something? I have loaded successfully in my side.
