### ISSUE TITLE
Chạy trên QEMU thì ok, còn chạy trên VirtualBox thì bị Exception

### ISSUE THREAD

**Issue by mountto** [nguyenzung/kos#26]
![VirtualBox_test_10_10_2022_09_40_50](https://user-images.githubusercontent.com/85049064/194880175-35364e79-4a5c-43e1-9407-7f436a6e1cac.png)

**Comment by nguyenzung** [comment]
Bạn tạo VM với 512MB RAM trở lên nhé

**Comment by nguyenzung** [comment]
Mình mới update thêm chỗ này

**Comment by mountto** [comment]
> 
mình tạo VirtualBox 1G hay 2G ram thì bị lỗi Exception, còn 512MB thì ok. Vậy là do đâu bạn, còn info Exception thì sao mình biết mã lỗi gì ?

**Comment by nguyenzung** [comment]
Vì mình đang đánh địa chỉ cố định cho khoảng 512MB.
