### ISSUE TITLE
Ý tưởng thiết kế Giao diện cho KOS

### ISSUE THREAD

**Issue by mountto** [nguyenzung/kos#27]
Theo mình thì giao diện full màn hình ̣̣đơn giản, trên cùng top là thanh ngang, chưá các Tabs ứng dụng và một tab Desktop.

**Comment by nguyenzung** [comment]
Mình chưa hình dung ra được.

**Comment by mountto** [comment]
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/85049064/195129006-b5a1b996-21a0-4305-a943-7184c459dc54.gif)
Kiểu như vậy nè

**Comment by nguyenzung** [comment]
Hay đấy bạn
HIện resolution hơi thấp, chỉ là 320*200, chắc cần upgrade thêm mới support đẹp đc

**Comment by mountto** [comment]
Mình cũng mong đợi nhìn thấy nó
