### ISSUE TITLE
Về ap.cpp và bsp.cpp để chạy các CPUs khác

### ISSUE THREAD

**Issue by mountto** [nguyenzung/kos#28]
Mình nghĩ sẽ gặp error khi áp dụng lên trên phần cứng.

**Comment by nguyenzung** [comment]
Error gì bạn nhỉ

**Comment by mountto** [comment]
When you start testing your SMP code on real machines, you'll realize that they do not keep the standard. You must not do Broadcast INIT IPIs nor Broadcast SIPIs. The following example has a decant amount of error checking to be used on real hardware
