### ISSUE TITLE
Làm sao đẩy lên được @nguyenzung

### ISSUE THREAD

**Issue by mountto** [nguyenzung/kos#30]
root@my-pc:/home/murt/gittest/test/kos# git push
remote: Permission to nguyenzung/kos.git denied to teonho.
fatal: unable to access 'https://github.com/nguyenzung/kos.git/': The requested URL returned error: 403

@nguyenzung

**Comment by nguyenzung** [comment]
Bạn tạo PR cho mình nhé

**Comment by mountto** [comment]
Làm trên web thì mình biết, còn cmd thì ko biết

**Comment by vuhailongkl97** [comment]
Lỗi là do bạn clone repo kos của dungnguyen.
How to fix.
1. Xoá repo kos trên account của bạn.
2. Vào repo kos của dungnguyen, nhấn fork.
3. Commit code lên repo của bạn, rồi tạo pull request
 Detail here : https://github.com/firstcontributions/first-contributions
