### ISSUE TITLE
qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory    

### ISSUE THREAD

**Issue by vuhailongkl97** [nguyenzung/kos#34]
Hi,
I have just tried to run the demonstration and met a problem when running the program with qemu.
I saw that you configured 8GB RAM for the demonstration. It's huge for my computer(the total RAM size is 8GB).
Is there any reason for that setting?
https://github.com/nguyenzung/kos/blob/85afed9052d08f83d25df44e28d37d0380419359/Makefile#L67

**Comment by mountto** [comment]
mình vào được cả Qemu và VirtualBox mà, đang load SVGA

**Comment by nguyenzung** [comment]
8GB RAM is for testing. You can set 512MB RAM.
