### ISSUE TITLE
Mình chạy thử make all thì link bị lỗi

### ISSUE THREAD

**Issue by daohainam** [nguyenzung/kos#36]
sudo make all
ld -o build/kernel.bin -T kernel.ld -nostdlib -n -Map=build/kernel.map  build/ui/logger.o  build/ui/label.o  build/ui/console.o  build/ui/window.o  build/ui/desktop.o  build/ui/font.o  build/ui/textinput.o  build/ui/button.o  build/stdlib/string.o  build/tasks/counter.o  build/tasks/ui.o  build/driver/keyboard.o  build/driver/timer.o  build/driver/cmos.o  build/driver/vga.o  build/driver/mouse.o  build/driver/serial.o  build/driver/vesa.o  build/kernel/sdt.o  build/kernel/taskmanager.o  build/kernel/task.o  build/kernel/stdout.o  build/kernel/memorymapper.o  build/kernel/stdin.o  build/kernel/os.o  build/kernel/utils.o  build/kernel/stdio.o  build/kernel/multiboot.o  build/kernel/process.o  build/kernel/basedriver.o  build/kernel/processor.o  build/kernel/main.o  build/kernel/pic.o  build/kernel/graphicsserver.o  build/kernel/iocommand.o  build/kernel/basegraphicsdevice.o  build/kernel/physicalmemory.o  build/kernel/ioapic.o  build/kernel/interruptmanager.o  build/kernel/heapmemorymanager.o  build/kernel/kernel.o  build/kernel/bsp.o  build/kernel/processmanager.o  build/kernel/virtualmemory.o  build/kernel/widget.o  build/kernel/printer.o  build/kernel/devicemanager.o  build/kernel/ap.o  build/kernel/apic.o  build/kernel/context.o  build/kernel/kernelobject.o  build/kernel/interrupthandler.o  build/kernel/gdt.o  build/kernel/RealMode.o  build/kernel/LongMode.o  build/kernel/utils86.o  build/kernel/ProtectedMode.o && \
cp build/kernel.bin iso/boot && \
grub-mkrescue /usr/lib/grub/x86_64-efi -o build/kos.iso iso
**ld: build/kernel/process.o: in function `kernel::Process::initializeVirtualMemory()':
process.cpp:(.text+0x1a7): undefined reference to `operator new(unsigned long, std::align_val_t)'
ld: build/kernel/process.o: in function `kernel::Process::initializeGDT()':
process.cpp:(.text+0x211): undefined reference to `operator new(unsigned long, std::align_val_t)'
make: *** [Makefile:43: build/kos.iso] Error 1**

**Comment by nguyenzung** [comment]
Hình như bạn chưa icó #include <kernel/heapmemorymanager.h>

Lệnh make all lâu mình k dùng. Mình chạy luôn make demo

**Comment by daohainam** [comment]
Lỗi này là lỗi link chứ không phải compile

**Comment by nguyenzung** [comment]
Mình đoán là bạn chưa setup cross-compile nên khi compile có thể sẽ link vào new của Linux. Nên bạn thử include file trên mình viết để sử dụng toán tử new.
