### ISSUE TITLE
More arch in Kos

### ISSUE THREAD

**Issue by mountto** [nguyenzung/kos#37]
Bạn nguyenzung, bạn add thêm arch Arm cho anh em develop đượ̣c ko.

**Comment by nguyenzung** [comment]
Mình k hiểu về Arm nên k biết add thêm như thế nào :(

**Comment by mountto** [comment]
qemu-system-x86_64 -smp 4,sockets=2,cores=2,maxcpus=4 -cpu host -m 8192M -serial file:kos_serial.log -no-reboot -no-shutdown -cdrom build/kos.iso --enable-kvm
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize kvm: No such file or directory
make: *** [Makefile:66: demo] Error 1
làm sao cài cái kvm này bạn

**Comment by nguyenzung** [comment]
Bạn cài KVM trên máy là chạy đc. Bạn check xem BIOS/UEFI đã enable chưa nhé
