### ISSUE TITLE
a question about SCREEN_MAP_MEM

### ISSUE THREAD

**Issue by vuhailongkl97** [nguyenzung/kos#7]
Hi,
I have a question about this line of code. Do you know what is the maximum size of SCREEN_MAP_MEM? I saw you increment the axis y without checking out of a bound.

https://github.com/nguyenzung/kos/blob/fd439a5b969871c7cd7ea4f999c3f3d51322693c/kernel/printer.cpp#L20

**Comment by mountto** [comment]
the maximum size of SCREEN_MAP_MEM, i think  128 KiB in size

**Comment by nguyenzung** [comment]
> Hi, I have a question about this line of code. Do you know what is the maximum size of SCREEN_MAP_MEM? I saw you increment the axis y without checking out of a bound.
> 
> https://github.com/nguyenzung/kos/blob/fd439a5b969871c7cd7ea4f999c3f3d51322693c/kernel/printer.cpp#L20

In Text Mode 80*25, we have memory mapped from 0xb8000 to 0xb8000 + (80 * 25 * 2), I check at the line 24 after added memove function for making scroll down when text is going to out of the screen

**Comment by vuhailongkl97** [comment]
got it, Do you have any idea for saving the data ?, I just implement a mouse driver, and I would like to improve it with a scroll wheeling feature.

**Comment by nguyenzung** [comment]
Not yet. Actually, i have plan to use Video Mode. Now, text mode is for debug.

**Comment by vuhailongkl97** [comment]
Ok, currently Is Video Mode VGA? Is it ready?

**Comment by nguyenzung** [comment]
> Ok, currently Is Video Mode VGA? Is it ready?

It is ready, but the resolution is low. I think it is better if having driver for thing like a native Intel graphics card

**Comment by nguyenzung** [comment]
> Ok, currently Is Video Mode VGA? Is it ready?

It is ready, but the resolution is low. I think it is better if having driver for thing like a native Intel graphics card

**Comment by vuhailongkl97** [comment]
oh, it sounds complicated, it may take more time to investigate.

**Comment by nguyenzung** [comment]
> oh, it sounds complicated, it may take more time to investigate.

Yep, but it is very interesting if the os have high resolution, right. :D

I am also trying to make an abstraction so that the os can run with multiple resolution. I think we will have a module name Graphics server. This module interacts with any graphics cards that have driver to draw screen. So that, we can still develop Window with VGA
